version: '3'
services:
  jabber:
    container_name: jabber
    image: jabber
    volumes:
      - ./jabber/config:/root/.mcabber
    command: /bin/sh -c 'tail -f /dev/null'
    stdin_open: true
    tty: true

